# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
                model_name='book',
                old_name='typ',
                new_name='category',
        ),
        migrations.RenameField(
                model_name='book',
                old_name='pubDate',
                new_name='publish_date',
        ),
        migrations.RenameField(
                model_name='img',
                old_name='desc',
                new_name='description',
        ),
        migrations.AlterField(
                model_name='myuser',
                name='permission',
                field=models.IntegerField(default=1),
        ),
    ]
